server:
  port: 8888
spring:
  rabbitmq:
    mqtt:
    #根据实际情况填写
    serverUri: tcp://ip(域名):1883
     #根据实际情况填写
    userName: test
     #根据实际情况填写
    password: mqtt_client_pass
     #根据实际情况填写
    topic: test.topic